export const linklist = [
	{ inputs: [], name: 'ErrCallerNotWeb3Entry', type: 'error' },
	{ inputs: [], name: 'ErrCallerNotWeb3EntryOrNotOwner', type: 'error' },
	{ inputs: [], name: 'ErrTokenNotExists', type: 'error' },
	{
		inputs: [
			{ indexed: true, name: 'from', type: 'uint256' },
			{ indexed: true, name: 'tokenId', type: 'uint256' },
		],
		name: 'Burn',
		type: 'event',
	},
	{
		inputs: [{ indexed: false, name: 'version', type: 'uint8' }],
		name: 'Initialized',
		type: 'event',
	},
	{
		inputs: [
			{ indexed: true, name: 'tokenId', type: 'uint256' },
			{ indexed: true, name: 'newlinkType', type: 'bytes32' },
		],
		name: 'LinkTypeSet',
		type: 'event',
	},
	{
		inputs: [
			{ indexed: true, name: 'from', type: 'address' },
			{ indexed: true, name: 'characterId', type: 'uint256' },
			{ indexed: true, name: 'tokenId', type: 'uint256' },
		],
		name: 'Transfer',
		type: 'event',
	},
	{
		inputs: [
			{ indexed: true, name: 'tokenId', type: 'uint256' },
			{ indexed: false, name: 'uri', type: 'string' },
		],
		name: 'UriSet',
		type: 'event',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'Uri',
		outputs: [{ name: '', type: 'string' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'Web3Entry',
		outputs: [{ name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'ethAddress', type: 'address' },
		],
		name: 'addLinkingAddress',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'toUri', type: 'string' },
		],
		name: 'addLinkingAnyUri',
		outputs: [{ name: '', type: 'bytes32' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'toCharacterId', type: 'uint256' },
		],
		name: 'addLinkingCharacterId',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'tokenAddress', type: 'address' },
			{ name: 'erc721TokenId', type: 'uint256' },
		],
		name: 'addLinkingERC721',
		outputs: [{ name: '', type: 'bytes32' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'linklistId', type: 'uint256' },
		],
		name: 'addLinkingLinklistId',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'toCharacterId', type: 'uint256' },
			{ name: 'toNoteId', type: 'uint256' },
		],
		name: 'addLinkingNote',
		outputs: [{ name: '', type: 'bytes32' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ name: 'account', type: 'address' }],
		name: 'balanceOf',
		outputs: [{ name: 'balance', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'characterId', type: 'uint256' }],
		name: 'balanceOf',
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'burn',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'characterOwnerOf',
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getCurrentTakeOver',
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkType',
		outputs: [{ name: '', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingAddressListLength',
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingAddresses',
		outputs: [{ name: '', type: 'address[]' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingAnyListLength',
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'linkKey', type: 'bytes32' }],
		name: 'getLinkingAnyUri',
		outputs: [{ name: '', type: 'string' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingAnyUriKeys',
		outputs: [{ name: '', type: 'bytes32[]' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingAnyUris',
		outputs: [{ name: 'results', type: 'string[]' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingCharacterIds',
		outputs: [{ name: '', type: 'uint256[]' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingCharacterListLength',
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'linkKey', type: 'bytes32' }],
		name: 'getLinkingERC721',
		outputs: [
			{
				components: [
					{ name: 'tokenAddress', type: 'address' },
					{ name: 'erc721TokenId', type: 'uint256' },
				],
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingERC721ListLength',
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingERC721s',
		outputs: [
			{
				components: [
					{ name: 'tokenAddress', type: 'address' },
					{ name: 'erc721TokenId', type: 'uint256' },
				],
				name: 'results',
				type: 'tuple[]',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingLinklistIds',
		outputs: [{ name: '', type: 'uint256[]' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingLinklistLength',
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'linkKey', type: 'bytes32' }],
		name: 'getLinkingNote',
		outputs: [
			{
				components: [
					{ name: 'characterId', type: 'uint256' },
					{ name: 'noteId', type: 'uint256' },
				],
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingNoteListLength',
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getLinkingNotes',
		outputs: [
			{
				components: [
					{ name: 'characterId', type: 'uint256' },
					{ name: 'noteId', type: 'uint256' },
				],
				name: 'results',
				type: 'tuple[]',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'getOwnerCharacterId',
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'name_', type: 'string' },
			{ name: 'symbol_', type: 'string' },
			{ name: 'web3Entry_', type: 'address' },
		],
		name: 'initialize',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'characterId', type: 'uint256' },
			{ name: 'linkType', type: 'bytes32' },
		],
		name: 'mint',
		outputs: [{ name: 'tokenId', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'name',
		outputs: [{ name: '', type: 'string' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'tokenId', type: 'uint256' }],
		name: 'ownerOf',
		outputs: [{ name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'ethAddress', type: 'address' },
		],
		name: 'removeLinkingAddress',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'toUri', type: 'string' },
		],
		name: 'removeLinkingAnyUri',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'toCharacterId', type: 'uint256' },
		],
		name: 'removeLinkingCharacterId',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'tokenAddress', type: 'address' },
			{ name: 'erc721TokenId', type: 'uint256' },
		],
		name: 'removeLinkingERC721',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'linklistId', type: 'uint256' },
		],
		name: 'removeLinkingLinklistId',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'toCharacterId', type: 'uint256' },
			{ name: 'toNoteId', type: 'uint256' },
		],
		name: 'removeLinkingNote',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'linkType', type: 'bytes32' },
		],
		name: 'setLinkType',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ name: 'tokenId', type: 'uint256' },
			{ name: 'uri', type: 'string' },
		],
		name: 'setUri',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ name: 'interfaceId', type: 'bytes4' }],
		name: 'supportsInterface',
		outputs: [{ name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'symbol',
		outputs: [{ name: '', type: 'string' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'totalSupply',
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
] as const
export type Linklist = typeof linklist
