/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Abi, AbiInterface } from "../Abi";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "approved",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "ApprovalForAll",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "linklistId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
    ],
    name: "attachLinklist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "string",
            name: "handle",
            type: "string",
          },
          {
            internalType: "string",
            name: "uri",
            type: "string",
          },
          {
            internalType: "address",
            name: "linkModule",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "linkModuleInitData",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.CreateProfileData",
        name: "profileData",
        type: "tuple",
      },
    ],
    name: "createProfile",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "createThenLinkProfile",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "linklistId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
    ],
    name: "detachLinklist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getApproved",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
    ],
    name: "getHandle",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getLinkModule4Address",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getLinkModule4ERC721",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "linklistId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "content",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.LinkData",
        name: "linkData",
        type: "tuple",
      },
    ],
    name: "getLinkModule4Link",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getLinkModule4Linklist",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
    ],
    name: "getLinkModule4Profile",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "getLinkingProfileIds",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLinklistContract",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "getLinklistUri",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "linklistId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "content",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.LinkData",
        name: "linkData",
        type: "tuple",
      },
    ],
    name: "getMintModule4Link",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "noteId",
        type: "uint256",
      },
    ],
    name: "getMintModule4Note",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "noteId",
        type: "uint256",
      },
    ],
    name: "getNoteUri",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getPrimaryProfileId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
    ],
    name: "getProfile",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "profileId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "handle",
            type: "string",
          },
          {
            internalType: "string",
            name: "uri",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "noteCount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "socialToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "linkModule",
            type: "address",
          },
        ],
        internalType: "struct DataTypes.Profile",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "handle",
        type: "string",
      },
    ],
    name: "getProfileByHandle",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "profileId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "handle",
            type: "string",
          },
          {
            internalType: "string",
            name: "uri",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "noteCount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "socialToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "linkModule",
            type: "address",
          },
        ],
        internalType: "struct DataTypes.Profile",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
    ],
    name: "getProfileUri",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
      {
        internalType: "address",
        name: "_linkListContract",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "isApprovedForAll",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
    ],
    name: "isPrimaryProfile",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "ethAddress",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "linkAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
    ],
    name: "linkAddressLink",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "toUri",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "linkAny",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "linkERC721",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "linkListId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "linkLinklist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "toProfileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "toNoteId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "linkNote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
    ],
    name: "linkNoteLink",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "toProfileId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "linkProfile",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
    ],
    name: "linkProfileLink",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "linklistId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "content",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.LinkData",
        name: "linkData",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mintAddressLink",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "linklistId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "content",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.LinkData",
        name: "linkData",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mintAnyLink",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "linklistId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "content",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.LinkData",
        name: "linkData",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mintERC721Link",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "linklistId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "content",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.LinkData",
        name: "linkData",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mintLinklistLink",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "noteId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mintNote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "linklistId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "content",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.LinkData",
        name: "linkData",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mintNoteLink",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "linklistId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "content",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.LinkData",
        name: "linkData",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mintProfileLink",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "profileId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "contentUri",
            type: "string",
          },
          {
            internalType: "address",
            name: "linkModule",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "linkModuleInitData",
            type: "bytes",
          },
          {
            internalType: "address",
            name: "mintModule",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "mintModuleInitData",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.PostNoteData",
        name: "noteData",
        type: "tuple",
      },
    ],
    name: "postNote",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "profileId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "contentUri",
            type: "string",
          },
          {
            internalType: "address",
            name: "linkModule",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "linkModuleInitData",
            type: "bytes",
          },
          {
            internalType: "address",
            name: "mintModule",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "mintModuleInitData",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.PostNoteData",
        name: "noteData",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "linklistId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "content",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.LinkData",
        name: "linkData",
        type: "tuple",
      },
    ],
    name: "postNoteWithLink",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "newHandle",
        type: "string",
      },
    ],
    name: "setHandle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "address",
        name: "linkModule",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "linkModuleInitData",
        type: "bytes",
      },
    ],
    name: "setLinkModule4Address",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "linkModule",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "linkModuleInitData",
        type: "bytes",
      },
    ],
    name: "setLinkModule4ERC721",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "linklistId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "content",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.LinkData",
        name: "linkData",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "linkModule",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "linkModuleInitData",
        type: "bytes",
      },
    ],
    name: "setLinkModule4Link",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "linkModule",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "linkModuleInitData",
        type: "bytes",
      },
    ],
    name: "setLinkModule4Linklist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "noteId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "linkModule",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "linkModuleInitData",
        type: "bytes",
      },
    ],
    name: "setLinkModule4Note",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "linkModule",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "linkModuleInitData",
        type: "bytes",
      },
    ],
    name: "setLinkModule4Profile",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "linkListId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    name: "setLinklistUri",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "linklistId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "content",
            type: "bytes",
          },
        ],
        internalType: "struct DataTypes.LinkData",
        name: "linkData",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "mintModule",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "mintModuleInitData",
        type: "bytes",
      },
    ],
    name: "setMintModule4Link",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "toNoteId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "mintModule",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "mintModuleInitData",
        type: "bytes",
      },
    ],
    name: "setMintModule4Note",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
    ],
    name: "setPrimaryProfileId",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "newUri",
        type: "string",
      },
    ],
    name: "setProfileUri",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "setSocialToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "tokenByIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "tokenOfOwnerByIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "ethAddress",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "unlinkAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "toProfileId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "unlinkProfile",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "linklistId",
        type: "uint256",
      },
    ],
    name: "AttachLinklist",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "BaseInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "linklistId",
        type: "uint256",
      },
    ],
    name: "DetachLinklist",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "toProfileId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "linklistId",
        type: "uint256",
      },
    ],
    name: "LinkProfile",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "LinklistNFTInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "noteId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "MintNFTInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "handle",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "ProfileCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "newHandle",
        type: "string",
      },
    ],
    name: "SetHandle",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "linkModule",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "returnData",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "SetLinkModule4Address",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "noteId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "linkModule",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "returnData",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "SetLinkModule4Note",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "linkModule",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "returnData",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "SetLinkModule4Profile",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "noteId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "mintModule",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "returnData",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "SetMintModule4Note",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
    ],
    name: "SetPrimaryProfileId",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "SetSocialToken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "fromProfileId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "toProfileId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "linkType",
        type: "bytes32",
      },
    ],
    name: "UnlinkProfile",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "Web3EntryInitialized",
    type: "event",
  },
];

export class Abi__factory {
  static readonly abi = _abi;
  static createInterface(): AbiInterface {
    return new utils.Interface(_abi) as AbiInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Abi {
    return new Contract(address, _abi, signerOrProvider) as Abi;
  }
}
