name: CI

on:
  push:
    branches: [main]
  # disable by temp
  # pull_request:
  #   branches: [main]

jobs:
  test:
    concurrency: 'test'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Unit Test
        run: pnpm run test
        env:
          VITE_MOCK_USER_ADDRESS: ${{ secrets.VITE_MOCK_USER_ADDRESS }}
          VITE_MOCK_USER_PRIVATE_KEY: ${{ secrets.VITE_MOCK_USER_PRIVATE_KEY }}

      - name: Type check
        run: pnpm run typecheck
