name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Get Tag Version
        id: get_tag_version
        run: echo "::set-output name=tag_version::${{ github.ref_name }}"

      - name: Check Tag Version
        run: |
          if [[ "${{ steps.get_tag_version.outputs.tag_version }}" < "v1.0.0" ]]; then
            echo "Tag version is below v1.0.0. Exiting workflow."
            return
          fi

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
